### ISSUE TITLE
nothing worng with this but i have a mod idea!

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SuperTeamXP/FNF-DUSTTALE-HTML5-Build#1]

**Comment by SubtleXP** [comment]
Since this isn’t an issue, make sure to add a label like “enhancement” or “question.” But what’s you’re mod idea?

**Comment by LEVIXDDLMAO** [comment]
So next can you make the tails.exe mod or the hd mod?

**Comment by SubtleXP** [comment]
Sure, I’m planning on doing Whitty and Matt, but I can do that too

**Comment by LEVIXDDLMAO** [comment]
Oh okay! I been wanting someone to do tails.exe mod- And Thank you!

**Comment by SubtleXP** [comment]
You’re welcome
