### ISSUE TITLE
hows it going?

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SuperTeamXP/FNF-DUSTTALE-HTML5-Build#2]

**Comment by SubtleXP** [comment]
Plans have changed, I’m making an FNF Multiplayer Indie Cross mod, and porting Indie Cross to html5, my multiplayer mod is almost done and a trailer will be posted on YouTube channel, and there other FNF mods I made and other things on my YouTube channel here https://www.youtube.com/channel/UCV6iTsL36PASu6fkxKLTNCg subscribe if you’re interested in my content and want more!

**Comment by LEVIXDDLMAO** [comment]
Dope! :D

**Comment by SuperTeamXP** [comment]
I see how you are get

**Comment by SubtleXP** [comment]
I see how you’re annoyed with fnfunblocked taking your fnf html5 ports and putting them on their website without asking, it happened to me with this repository too

**Comment by anime-kun32** [comment]
hey is it ok if i can add some mods to this as well and make a pull request

**Comment by SubtleXP** [comment]
@anime-kun32 Sure. This place is ancient anyway
